### ISSUE TITLE
Improvements to the "Implementing a new Discovery Handler" Doc

### ISSUE THREAD

**Issue by jiayihu** [project-akri/akri#342]
I would like to point some ideas for improvements while following the documentation.

- A brief explanation of what gRPC is could be useful, maybe just a link if we assume everyone working on Kubernetes has at least heard of it
- I didn't know what `UDS` was. It's always better to write the extended words the first time for better clarity.
- The point about implementing the discovery logic should be extended, as it is the most crucial part. Should at least point to `debug-echo` as the default example to follow
- In section https://github.com/deislabs/akri/blob/main/docs/discovery-handler-development.md#specifying-device-filtering-in-a-configuration, I believe it would be clearer to explain that the Configuration will be set later during the Helm install. Otherwise, it's not clear how is the agent supposed to know it and pass it to the discovery handler.

About the template:
- `deserialize_discovery_details, DISCOVERED_DEVICES_CHANNEL_CAPACITY` are not imported, although fundamental for the discovery
- What is `register_sender`? It isn't even commented on the other protocol implementations, such as debug-echo. Obv, by following the implementation one understands that it's just a synchronisation mechanism to try re-registration to the agent
- Why is the type `register_sender: tokio::sync::mpsc::Sender<()>` in the template, while it's `Option`al in the rest of the protocols?
- The Dockerfile should have the `RUST_LOG` enabled

**Comment by kate-goldenring** [comment]
@jiayihu these are all great points, and I will update the template with your suggestions. The `register_sender` in Akri's Discovery Handlers is wrapped in an Option because if they are compiled into the agent (as with an agent build with the `agent-full` flag) then they never need to register nor re-register. 

Would you be interested in modifying the discovery handler documentations with your suggestions?
