### ISSUE TITLE
[Outdated Sample] Discovering and Using OPC UA Thermometers

### ISSUE THREAD

**Issue by fawohlsc** [project-akri/akri#464]
**Describe the bug**
The setup of the [OPC UA Servers](https://docs.akri.sh/demos/opc-thermometer-demo#creating-opc-ua-servers) in the sample [Discovering and Using OPC UA Thermometers](https://docs.akri.sh/demos/opc-thermometer-demo#creating-opc-ua-servers) is outdated i.e., referenced line numbers in source code and dotnet project names.

**Expected behavior**
Sample should be updated or OPC UA server should be replaced e.g., by [OPC PLC server](https://github.com/azure-samples/iot-edge-opc-plc/). OPC PLC server is already containerized which would simplify the OPC UA Server setup in the sample.

**Comment by kate-goldenring** [comment]
@fawohlsc sorry for the delay here. Updating to use the OPC PLC server in the demo would vastly simplify it and make it less prone to getting outdated again. Were you able to successfully try out Akri with the  OPC PLC server?

**Comment by fawohlsc** [comment]
@kate-goldenring no worries and thanks for following up. 

**Short-answer:** _No_

**Long answer:**
The [OPC PLC server](https://github.com/azure-samples/iot-edge-opc-plc/) comes with its own simulated values, hence it would require to amend the sample code to target different OPC UA nodes and values. Screenshot taken from [ProSys OPC UA Browser](https://www.prosysopc.com/products/opc-ua-browser/):
![Screenshot 2022-04-05 131231](https://user-images.githubusercontent.com/41372128/161741934-7265d5d1-4f38-4400-918a-76399d87d038.png)

We actually got your sample running by leveraging the free [ProSys OPC UA Simulation Server](https://prosysopc.com/products/opc-ua-simulation-server). Basically, by modelling the OPC UA nodes and values according to your sample. Screenshot  taken from [ProSys OPC UA Simulation Server](https://prosysopc.com/products/opc-ua-simulation-server):
![image](https://user-images.githubusercontent.com/41372128/161740427-6fd61839-1f6e-4036-ad7d-40a2e865db15.png)

Overall, I believe changing the sample by replacing the .NET OPC UA Server with either [ProSys OPC UA Simulation Server](https://prosysopc.com/products/opc-ua-simulation-server) or [OPC PLC server](https://github.com/azure-samples/iot-edge-opc-plc/) should be a good fix for the sample. Personally, I would prefer the [OPC PLC server](https://github.com/azure-samples/iot-edge-opc-plc/), since it is just running the server as a container - super easy to setup. Unfortunately, this would require to also update your sample code to target the different OPC UA nodes and values. 

What do you think?

**Comment by fawohlsc** [comment]
@kate-goldenring - I would love to, but honestly cannot commit to it at the moment due to lack of free capacity.

**Comment by kate-goldenring** [comment]
@fawohlsc I updated the demo to point to the appropriate tag of the .NET library so that the demo can be followed again: https://github.com/project-akri/akri-docs/pull/31. I agree that changing to the PLC containers would make for a simpler demo -- maybe one we can add soon.

**Comment by kate-goldenring** [comment]
Also, using this thread to track progress on using the OPC PLC server. Already, it is easy to discover the server with Akri with the following flow:
1. Run the server according to its [readme](https://github.com/Azure-Samples/iot-edge-opc-plc)
1. Install Akri where $HOST_SERVER_IP is the ip address of the machine running the containerized PLC OPC UA server 
  ```
  helm install akri akri-helm-charts/akri \
       $AKRI_HELM_CRICTL_CONFIGURATION \
       --set opcua.discovery.enabled=true \
       --set opcua.configuration.enabled=true \
        --set opcua.configuration.discoveryDetails.discoveryUrls[0]="opc.tcp://$HOST_SERVER_IP:50000/" 
  ```
3. See the discovered instances: `kubectl get akrii`

The broker should be able to be used with this server out of the box. I ran into issues with credentials, so i believe generating certs for the PLC server and the broker would resolve it, but the following is a flow that could be turned on with a little more debugging:
1. Run the [server](https://github.com/Azure-Samples/iot-edge-opc-plc), using the flag `--nodesfile nodesfile.json` to point to [their sample nodes file](https://github.com/Azure-Samples/iot-edge-opc-plc#user-node-configuration-via-json-configuration-file)
2. Install Akri, specifying which of the nodes in the `nodesfile.json` to track -- in this case the DKW node. Namespace index is `2` because it is one below the root folder.
  ```
  helm install akri akri-helm-charts/akri \
       $AKRI_HELM_CRICTL_CONFIGURATION \
       --set opcua.discovery.enabled=true \
       --set opcua.configuration.enabled=true \
        --set opcua.configuration.discoveryDetails.discoveryUrls[0]="opc.tcp://10.137.184.115:50000/" \
       --set opcua.configuration.name=akri-opcua-monitoring \
       --set opcua.configuration.brokerPod.image.repository="ghcr.io/project-akri/akri/opcua-monitoring-broker" \
       --set opcua.configuration.brokerProperties.IDENTIFIER='MyTelemetry_DKW' \
       --set opcua.configuration.brokerProperties.NAMESPACE_INDEX='2'
  ```
3. The values of that node should be being served over a gRPC interface by the broker.

**Comment by fawohlsc** [comment]
@kate-goldenring - Many thanks for swiftly fixing the demo. Regarding your note _"I ran into issues with credentials, so i believe generating certs for the PLC server and the broker would resolve it"_ - Agree using certificates would be the most secure and realistic scenario. Another simpler option, would be to start the OPC PLC server with additional [command line flags](https://github.com/azure-samples/iot-edge-opc-plc/#command-line-reference) like `--unsecuretransport`.
