### ISSUE TITLE
Fix clippy error: use of `ok_or` followed by a function call

### ISSUE THREAD

**Issue by romoh** [project-akri/akri#467]
**Describe the bug**
Clippy error: use of `ok_or` followed by a function call 
more details: https://github.com/project-akri/akri/runs/5780368279?check_suite_focus=true

**To Reproduce**
https://github.com/project-akri/akri/runs/5780368279?check_suite_focus=true

**Expected behavior**
No errors.

**Logs (please share snips of applicable logs)**
https://github.com/project-akri/akri/runs/5780368279?check_suite_focus=true

**Additional context**
N/A

**Comment by kate-goldenring** [comment]
@Ragnyll are you able to take this one on?

**Comment by Ragnyll** [comment]
@kate-goldenring  got it. I'll work on this this week.

**Comment by Ragnyll** [comment]
Oddly enough i can only replicate this after i update dependencies. This strikes as me as odd that the lint would propagate only at the test level in akri's crates since this seems to tie only to the dependency update. 

I'm still going to fix this, but I'm running a cargo update with this as well which will invalidate #466 .  

I think we probably should discuss the auto-update dependency bot and how we should handle these kinds of errors for potential future breakages. I'd say just push another commit on top of the auto-update pr if this happens again.

**Comment by Ragnyll** [comment]
Opened https://github.com/project-akri/akri/pull/471
