### ISSUE TITLE
Allow for udev rules without devnode

### ISSUE THREAD

**Issue by agracey** [project-akri/akri#521]
**Is your feature request related to a problem? Please describe.**

I'm trying to get Akri to detect if a display is connected or not then schedule an X11 container to it. I found the correct rule but Akri doesn't seem to like it. 

**Is your feature request related to a way you would like Akri extended? Please describe.**

Currently, when I use the rule `SUBSYSTEM=="drm", ATTR{status}=="connected"` I see the below in the logs:

`find_devices - ignoring device with devpath "/devices/pci0000:00/0000:00:02.0/drm/card0/card0-DP-1" due to having no devnode`

I would imagine this is because the `drm` subsystem is at `/sys/class/drm/`?

**Describe the solution you'd like**
I would like for udev rules without devnodes to be allowed in the udev discovery handler

**Describe alternatives you've considered**
I don't think there are alternatives?

**Comment by agracey** [comment]
I'm looking at the traceback from https://github.com/project-akri/akri/blob/4cad8e767a7d67e0338cdf5da8d8cee4edb16d92/discovery-handlers/udev/src/discovery_impl.rs#L157 

I think there might be 2 options: 
- I build a custom discovery handler based on the udev handler that uses something other than devnode
- If `get_devnode(&device)` returns `None`, you could optionally return a predictable name based on the KERNEL or SUBSYSTEM and the node name

**Comment by kate-goldenring** [comment]
Hi @agracey. I think option 1 is a good route and one that we have discussed before in Slack (https://kubernetes.slack.com/archives/C01D9L7QE8Z/p1662486545856829?thread_ts=1662022333.544559&cid=C01D9L7QE8Z). It seems that using syspath rather than devnode would be more ideal which would keep device ids more deterministic too.

**Comment by agracey** [comment]
I went with option 1: https://github.com/agracey/display-discovery and it works! 

An example of it's use is here: https://gist.github.com/agracey/96cfa8c150687ec43b0ca18d42c05332 

Should I close this? Or rename to reflect the previously discussed syspath change that you linked (for some reason slack isn't deep-linking for me so I can't actually see  the conversation ☹️)?

**Comment by kate-goldenring** [comment]
@agracey looks like you are [using devpath if devnode does not exist](https://github.com/agracey/display-discovery/blob/e395e2e242d14f6829a69210a7e82b4f26682622/src/discovery_handler.rs#L149). Should we just always use devpath/syspath? Then rather than a custom DH we could just update the current udev one? Great that you were able to create a DH to get things going in the meantime.

**Comment by agracey** [comment]
🎉  Thank you!
