### ISSUE TITLE
Akri agent fails to start in managed GKE cluster

### ISSUE THREAD

**Issue by bfjelds** [project-akri/akri#70]
**Describe the bug**
When starting Akri in Google Cloud Platform cluster, the agent failed to start, complaining about mounting crictl from read-only file-system.

`kubectl get pods -o wide`
```sh
NAME                                          READY   STATUS             RESTARTS   AGE    IP            NODE                                          NOMINATED NODE   READINESS GATES
akri-agent-daemonset-jr7pl                    0/1     CrashLoopBackOff   5          4m7s   10.128.0.12   gke-cluster-1-16-default-pool-c4e0f4c9-lthv   <none>           <none>
akri-agent-daemonset-trwqm                    0/1     CrashLoopBackOff   5          4m7s   10.128.0.10   gke-cluster-1-16-default-pool-c4e0f4c9-xlsx   <none>           <none>
akri-agent-daemonset-wq77x                    0/1     CrashLoopBackOff   5          4m7s   10.128.0.11   gke-cluster-1-16-default-pool-c4e0f4c9-tbdm   <none>           <none>
akri-controller-deployment-5957d7d7cc-z8rnx   1/1     Running            0          4m6s   10.64.1.7     gke-cluster-1-16-default-pool-c4e0f4c9-lthv   <none>           <none>
```

**Kubernetes Version: 1.16.13-gke.401**

**To Reproduce**
1. Create cluster using GCP: 1.16.13-gke.401
2. helm install akri akri-helm-charts/akri --set debugEcho.enabled=true --set debugEcho.name=debug-echo --set debugEcho.shared=false --set agent.allowDebugEcho=true --debug --set controller.onlyOnMaster=false

**Expected behavior**
Expect Akri controller and agent to start without error.  Akri controller starts.  Akri agent fails:

`kubectl describe pod $(kubectl get pods | grep agent | awk '{print $1}' | head -1)`
```sh
Events:
  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  7m39s                   default-scheduler  Successfully assigned default/akri-agent-daemonset-jr7pl to gke-cluster-1-16-default-pool-c4e0f4c9-lthv
  Warning  Failed     6m55s (x4 over 7m37s)   kubelet            Error: failed to start container "akri-agent": Error response from daemon: error while creating mount source path '/usr/bin/crictl': mkdir /usr/bin/crictl: read-only file system
  Normal   Pulling    6m10s (x5 over 7m38s)   kubelet            Pulling image "ghcr.io/deislabs/akri/agent:v0.0.36-dev"
  Normal   Pulled     6m9s (x5 over 7m37s)    kubelet            Successfully pulled image "ghcr.io/deislabs/akri/agent:v0.0.36-dev"
  Normal   Created    6m9s (x5 over 7m37s)    kubelet            Created container akri-agent
  Warning  BackOff    2m34s (x23 over 7m35s)  kubelet            Back-off restarting failed container
```

**Comment by ammmze** [comment]
I get the same error on my self-hosted k8s cluster running on [Talos](https://talos.dev). As far as I cant tell `crictl` is not present on Talos and getting it installed on the host would be a bit of a hassle because there is no shell access to Talos. It's an API driven and immutable operating system. Basically the only way to get `crictl` on the host is gonna be to have a job that mounts a host path directory, downloads and extracts crictl. But also this would need to happen prior to the agent starting up, otherwise when the agent attempts to mount it (for example I set the path to `/var/lib/akri/bin/crictl`) it ends up creating that full path as a directory on the host. So this effectively creates a race condition for either producing a file or a directory at `/var/lib/akri/bin/crictl`.

I'm not really familiar with `crictl`. Does it NEED to live on the host? Perhaps we could have an option in the helm chart that would add an init container that downloads and extracts it to an emptyDir mount that could be mounted by the agent?

**Comment by bfjelds** [comment]
interesting.  `crictl` is used by Akri to query the existing containers (it is needed because the Kubernetes Device-Plugin system doesn't notify when a scheduled pod/container dies/crashes/finishes).

i'm not sure it needs to be on the host ... it probably just needs access to Kubernetes' container socket.  maybe it can be installed in the agent container?
